In [1]:
import numpy as np

Creación básica de matrices

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a = np.ones(3)
a

array([1., 1., 1.])

In [5]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
a = np.random.random(5)
a

array([0.54223346, 0.46596886, 0.93063275, 0.68919266, 0.09332288])

In [8]:
a = np.random.random((3, 3))
a

array([[0.91381252, 0.68718966, 0.30922912],
       [0.14403607, 0.55182958, 0.92774983],
       [0.99418928, 0.01012449, 0.99645499]])

In [20]:
c = np.empty(5)
c

array([0.54223346, 0.46596886, 0.93063275, 0.68919266, 0.09332288])

In [21]:
a = np.full(5, 666)
a

array([666, 666, 666, 666, 666])

In [22]:
a = np.full((3, 3), 666)
a

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [23]:
a = np.arange(0, 10, 2)
a

array([0, 2, 4, 6, 8])

In [25]:
a = np.linspace(0, 5, 10)
a

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])